const AUTOMALL_TODO = [
    { name: "iron-gear-wheel",      start_count: 10,  stop_count: 190 },
    { name: "transport-belt",       start_count: 10,  stop_count: 90 },
    { name: "underground-belt",     start_count: 1,   stop_count: 5 },
    { name: "copper-cable",         start_count: 10,  stop_count: 190 },
    { name: "electronic-circuit",   start_count: 10,  stop_count: 290 },
    { name: "splitter",             start_count: 1,   stop_count: 5 },
    { name: "inserter",             start_count: 10,  stop_count: 60 },
    { name: "long-handed-inserter", start_count: 10,  stop_count: 40 },
    { name: "fast-inserter",        start_count: 10,  stop_count: 40 },
    { name: "repair-pack",          start_count: 10,  stop_count: 100 },
    { name: "pipe",                 start_count: 10,  stop_count: 200 },
    { name: "pipe-to-ground",       start_count: 10,  stop_count: 20 },
    { name: "assembling-machine-1", start_count: 10,  stop_count: 80 },
    { name: "electric-mining-drill",start_count: 10,  stop_count: 20 },
    { name: "steam-engine",         start_count: 10,  stop_count: 20 },
    { name: "radar",                start_count: 1,   stop_count: 5 },
    { name: "constant-combinator",  start_count: 1,   stop_count: 5 },
    { name: "decider-combinator",   start_count: 1,   stop_count: 5 },
    { name: "arithmetic-combinator",start_count: 1,   stop_count: 5 },
    { name: "power-switch",         start_count: 1,   stop_count: 5 },
    { name: "iron-stick",           start_count: 10,  stop_count: 200 },
    { name: "programmable-speaker", start_count: 1,   stop_count: 5 },
    { name: "display-panel",        start_count: 1,   stop_count: 5 },
    { name: "small-lamp",           start_count: 10,  stop_count: 20 },
    { name: "rail-signal",          start_count: 1,   stop_count: 5 },
    { name: "rail-chain-signal",    start_count: 1,   stop_count: 5 },
    { name: "iron-chest",           start_count: 10,  stop_count: 20 },
    { name: "offshore-pump",        start_count: 10,  stop_count: 20 },
    { name: "steel-chest",          start_count: 10,  stop_count: 20 },
    { name: "storage-tank",         start_count: 10,  stop_count: 50 },
    { name: "medium-electric-pole", start_count: 10,  stop_count: 20 },
    { name: "chemical-plant",       start_count: 10,  stop_count: 20 },
    { name: "assembling-machine-2", start_count: 10,  stop_count: 20 },
    { name: "big-electric-pole",    start_count: 10,  stop_count: 20 },
    { name: "engine-unit",          start_count: 10,  stop_count: 300 },
    { name: "pump",                 start_count: 10,  stop_count: 20 },
    { name: "pumpjack",             start_count: 10,  stop_count: 20 },
    { name: "train-stop",           start_count: 1,   stop_count: 5 },
    { name: "locomotive",           start_count: 1,   stop_count: 5 },
    { name: "cargo-wagon",          start_count: 1,   stop_count: 5 },
    { name: "fluid-wagon",          start_count: 1,   stop_count: 5 },
    { name: "car",                  start_count: 1,   stop_count: 5 },
    { name: "barrel",               start_count: 10,  stop_count: 20 },
    { name: "iron-gear-wheel",      start_count: 250, stop_count: 1000 },
    { name: "underground-belt",     start_count: 10,  stop_count: 100 },
    { name: "splitter",             start_count: 10,  stop_count: 100 },
    { name: "transport-belt",       start_count: 200, stop_count: 1000 },
    { name: "fast-transport-belt",  start_count: 100, stop_count: 200 },
    { name: "fast-underground-belt",start_count: 10,  stop_count: 50 },
    { name: "copper-cable",         start_count: 200, stop_count: 500 },
    { name: "electronic-circuit",   start_count: 200, stop_count: 500 },
    { name: "fast-splitter",        start_count: 10,  stop_count: 50 },
    { name: "solar-panel",          start_count: 10,  stop_count: 500 },
    { name: "heat-exchanger",       start_count: 10,  stop_count: 20 },
    { name: "steam-turbine",        start_count: 10,  stop_count: 20 },
    { name: "heat-pipe",            start_count: 10,  stop_count: 100 }
];

